//
// Created by Freyj on 13/05/2026.
//

#ifndef BS_THINGY_CONFIG_H
#define BS_THINGY_CONFIG_H

#define PORT 8080
#define BUFFER_SIZE 1024
#define MAX_PENDING_CONNECTIONS 10
#define MAX_TOPICS 20
#define MAX_SUBSCRIBERS_PER_TOPIC 10
#define TOPIC_NAME_SIZE 64

#endif //BS_THINGY_CONFIG_H

